language: python

services: mongodb

sudo: true

python:
  - "3.6"

before_install:
  - sudo apt-get install -y libgomp1

addons:
  apt:
    update: true

install:
  - pip install pipenv
  - pipenv install
  - pipenv sync -d

script:
  - pytest
  - pylint --rcfile .pylintrc wipm

branches:
  only:
    - master
