language: python

services: mongodb

sudo: true

python:
  - "3.6"

os:
  - osx

addons:
  homebrew:
    packages:
      - pipenv
      - gcc@7
    update: true

install:
  - pipenv install
  - pipenv sync -d

script:
  - pytest
  - pylint --rcfile .pylintrc wipm

branches:
  only:
    - master
