language: python

services: mongodb

sudo: true

python:
  - "3.6"

install:
  - sudo apt-get -y update && sudo apt-get -y upgrade
  - sudo apt-get install -y libgomp1 
  - pip install pipenv
  - pipenv install
  - pipenv sync -d

script:
  - pytest
  - pylint --rcfile .pylintrc wipm

branches:
  only:
    - master
