language: python

services: mongodb

python:
  - "3.6"

install:
  - apt-get install libgomp1 
  - pip install pipenv
  - pipenv install
  - pipenv sync -d

script:
  - pytest
  - pylint --rcfile .pylintrc wipm

branches:
  only:
    - master
